/****** Object:  Table [dbo].[HousingArea]    Script Date: 09/12/2018 22:32:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HousingArea](
	[AreaId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](150) NOT NULL,
 CONSTRAINT [PK_HousingArea] PRIMARY KEY CLUSTERED 
(
	[AreaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRA]    Script Date: 09/12/2018 22:32:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRA](
	[TRAId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](150) NOT NULL,
	[AreaId] [int] NOT NULL,
	[Email] [varchar](50) NULL,
	[PatchId] [uniqueidentifier] NULL,
	[Notes] [varchar](max) NULL,
 CONSTRAINT [PK_TRA] PRIMARY KEY CLUSTERED 
(
	[TRAId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRAEstates]    Script Date: 09/12/2018 22:32:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRAEstates](
	[TRAId] [int] NOT NULL,
	[EstateUHRef] [varchar](50) NOT NULL,
	[EstateName] [varchar](100) NULL,
 CONSTRAINT [PK_TRAEstates_1] PRIMARY KEY CLUSTERED 
(
	[TRAId] ASC,
	[EstateUHRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRAPatchAssociation]    Script Date: 09/12/2018 22:32:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRAPatchAssociation](
	[TRAId] [int] NOT NULL,
	[PatchCRMId] [varchar](150) NOT NULL,
 CONSTRAINT [PK_TRAPatchAssociation] PRIMARY KEY CLUSTERED 
(
	[TRAId] ASC,
	[PatchCRMId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRARoleAssignments]    Script Date: 09/12/2018 22:32:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRARoleAssignments](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TRAId] [int] NOT NULL,
	[ContactId] [varchar](150) NULL,
	[RoleId] [int] NOT NULL,
	[PersonName] [varchar](100) NULL,
 CONSTRAINT [PK_TRARoleAssignments] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRARoles]    Script Date: 09/12/2018 22:32:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRARoles](
	[RoleId] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [varchar](150) NOT NULL,
 CONSTRAINT [PK_TRARoles] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRA]  WITH CHECK ADD  CONSTRAINT [FK_TRA_Area] FOREIGN KEY([AreaId])
REFERENCES [dbo].[HousingArea] ([AreaId])
GO
ALTER TABLE [dbo].[TRA] CHECK CONSTRAINT [FK_TRA_Area]
GO
ALTER TABLE [dbo].[TRAEstates]  WITH CHECK ADD  CONSTRAINT [FK_TRAEstates_TRA] FOREIGN KEY([TRAId])
REFERENCES [dbo].[TRA] ([TRAId])
GO
ALTER TABLE [dbo].[TRAEstates] CHECK CONSTRAINT [FK_TRAEstates_TRA]
GO
ALTER TABLE [dbo].[TRAPatchAssociation]  WITH CHECK ADD  CONSTRAINT [FK_TRAPatchAssosiation_TRA] FOREIGN KEY([TRAId])
REFERENCES [dbo].[TRA] ([TRAId])
GO
ALTER TABLE [dbo].[TRAPatchAssociation] CHECK CONSTRAINT [FK_TRAPatchAssosiation_TRA]
GO
ALTER TABLE [dbo].[TRARoleAssignments]  WITH CHECK ADD  CONSTRAINT [FK_TRARoleAssignments_Roles] FOREIGN KEY([RoleId])
REFERENCES [dbo].[TRARoles] ([RoleId])
GO
ALTER TABLE [dbo].[TRARoleAssignments] CHECK CONSTRAINT [FK_TRARoleAssignments_Roles]
GO
ALTER TABLE [dbo].[TRARoleAssignments]  WITH CHECK ADD  CONSTRAINT [FK_TRARoleAssignments_TRA] FOREIGN KEY([TRAId])
REFERENCES [dbo].[TRA] ([TRAId])
GO
ALTER TABLE [dbo].[TRARoleAssignments] CHECK CONSTRAINT [FK_TRARoleAssignments_TRA]
GO
