using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ManageATenancyAPI.Models
{
    public class CRMServiceRequest
    {

        public CRMServiceRequest()
        {

        }

        /// <summary>
        /// IGNORE - AUTO GENERATED BY CRM
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// IGNORE - NOT REQUIRED 
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Issue.Notes for ETRA Issues
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// IGNORE - Customer from the Contacts Entity - Can be ignored for ETRA as has it's own Account 
        /// </summary>
        public string ContactId { get; set; }


        /// <summary>
        /// IGNORE - NOT USED FOR ETRA
        /// </summary>
        public string ParentCaseId { get; set; }

        /// <summary>
        /// CRM Subjects Entity Table, List of Values in Ticket
        /// </summary>
        public string Subject { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string CreatedDate { get; set; }
        public string EnquiryType { get; set; }
        /// <summary>
        /// Autogenerated by CRM
        /// </summary>
        public string TicketNumber { get; set; }
        /// <summary>
        /// Old requirement - not used anymore
        /// </summary>
        public bool RequestCallback { get; set; }
        /// <summary>
        /// For transferring tickets to other Housing Officers
        /// </summary>
        public bool Transferred { get; set; }
        /// <summary>
        /// Officer Id
        /// </summary>
        public string CreatedBy { get; set; }

        public List<CRMServiceRequest> ChildRequests { get; set; }
    }


}